package org.parser.util;

import org.parser.models.Film;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

public class TestFilmCreator {
    public static List<Film> defaultFilmOutput;

    static {
        try {
            defaultFilmOutput = List.of(
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/o279ba432def0ps78v52k.jpg"),
                            "Italian Best Shorts 6: Дом, милый дом",
                            "Italian Best Shorts 6",
                            2023,
                            "Италия",
                            "Драмы",
                            new URL("file:src/test/resources/3/film24.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/4/bbcfaf764a177xa66s30s.jpg"),
                            "Обжигающе горячий",
                            "Flamin' Hot",
                            2023,
                            "США",
                            "Драмы",
                            new URL("file:src/test/resources/2/film8.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/4/ld76e61db9a90km17q18r.jpg"),
                            "Позаботьтесь о Майе",
                            "Take Care of Maya",
                            2023,
                            "США",
                            "Документальные",
                            new URL("file:src/test/resources/2/film10.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/27/fc6b233cafd2ezf50q61u.jpg"),
                            "В тылу врага / Сражайся!",
                            "Come Out Fighting / Hymth",
                            2022,
                            "США",
                            "Боевики",
                            new URL("file:src/test/resources/5/film14.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/2/k5e87c51c8debqw36s12i.jpg"),
                            "Что движет нами",
                            "What Drives Us",
                            2021,
                            "США",
                            "Документальные",
                            new URL("file:src/test/resources/2/film28.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/2/da0c248e5770afj15f42j.jpg"),
                            "Последняя ночь Аморе",
                            "L'ultima notte di Amore / Last Night of Amore",
                            2023,
                            "Италия",
                            "Триллеры",
                            new URL("file:src/test/resources/2/film36.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/27/rb68eb1c7df59hm97e73j.jpg"),
                            "Том Папа: Ты отлично справляешься!",
                            "Tom Papa: You're Doing Great!",
                            2020,
                            "США",
                            "Стендап",
                            new URL("file:src/test/resources/5/film4.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/28/u1141eb122c1att59b76p.jpg"),
                            "Жить дальше",
                            "Moving On",
                            2022,
                            "США",
                            "Комедии",
                            new URL("file:src/test/resources/4/film17.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/3/k390d725f98b4ol78y64t.jpg"),
                            "SuperАлиби 2",
                            "Alibi.com 2",
                            2023,
                            "Франция",
                            "Комедии",
                            new URL("file:src/test/resources/4/film9.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/z6974ca730bc0he72x31x.jpg"),
                            "Пятнадцать минут позора",
                            "15 Minutes of Shame",
                            2021,
                            "США",
                            "Документальные",
                            new URL("file:src/test/resources/3/film11.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/27/kcad1f010efcesl27g31i.jpg"),
                            "Тайны Авроры Тигарден: Кради и ищи",
                            "Aurora Teagarden Mysteries: Heist and Seek",
                            2020,
                            "США",
                            "Детективы",
                            new URL("file:src/test/resources/5/film18.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/2/ne3fc486473bbhp86p52c.jpg"),
                            "Быть Сальвадором Дали",
                            "Dalíland",
                            2022,
                            "США",
                            "Драмы",
                            new URL("file:src/test/resources/3/film7.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/5/e1fc64af59c6duo78z33r.jpeg"),
                            "Людвиг ван Бетховен",
                            "Louis van Beethoven",
                            2020,
                            "Германия",
                            "Драмы",
                            new URL("file:src/test/resources/1/film6.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/pa3ee8d5cd252gh66d47o.jpg"),
                            "Победить или умереть",
                            "Vaincre ou mourir",
                            2022,
                            "Франция",
                            "Боевики",
                            new URL("file:src/test/resources/3/film16.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/gcfa856250029lj83m62r.jpg"),
                            "Спуск: Новая глава",
                            "Dark Nature",
                            2022,
                            "Канада",
                            "Ужасы",
                            new URL("file:src/test/resources/3/film18.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/y7d98345b296cjp46f36o.jpg"),
                            "40 лет Рокки: Рождение классики",
                            "40 Years of Rocky: The Birth of a Classic / Becoming Rocky: The Birth of a Classic",
                            2020,
                            "США",
                            "Документальные",
                            new URL("file:src/test/resources/3/film21.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/ndafaff4edc56vp77f86n.jpg"),
                            "Собака-герой: Путешествие домой",
                            "Hero Dog: The Journey Home",
                            2021,
                            "Канада",
                            "Приключения",
                            new URL("file:src/test/resources/3/film15.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/5/x82937ac77c0amt67q50f.jpg"),
                            "Расследования Джейн: Утерянное наследство",
                            "The Jane Mysteries: Inheritance Lost",
                            2023,
                            "Канада",
                            "Детективы",
                            new URL("file:src/test/resources/1/film18.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/5/a8f5499b094aavt47o52n.jpg"),
                            "Хоть что-то хорошее",
                            "Einfach mal was Schönes / Just Something Nice",
                            2022,
                            "Германия",
                            "Мелодрамы",
                            new URL("file:src/test/resources/1/film17.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/3/r66cc6b2dd169ur28q87b.jpg"),
                            "Милейшие мертвецы / Гражданская смерть",
                            "The Civil Dead",
                            2022,
                            "США",
                            "Комедии",
                            new URL("file:src/test/resources/2/film16.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/2/ffac0715fbb33ka43q84j.jpg"),
                            "Неделя в раю",
                            "A Week in Paradise",
                            2022,
                            "Великобритания",
                            "Мелодрамы",
                            new URL("file:src/test/resources/3/film5.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/4/aec8a0419add7de11r98q.jpg"),
                            "Время атома / Атомная энергетика сегодня",
                            "Nuclear Now / Nuclear",
                            2022,
                            "США",
                            "Документальные",
                            new URL("file:src/test/resources/2/film9.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/2/veb683329fb74kq89j83w.jpg"),
                            "Что видно отсюда",
                            "Was man von hier aus sehen kann",
                            2022,
                            "Германия",
                            "Драмы",
                            new URL("file:src/test/resources/3/film6.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/2/pc473ca4903c5tt54p78f.jpg"),
                            "Путаница",
                            "Mixed Baggage",
                            2022,
                            "Канада",
                            "Мелодрамы",
                            new URL("file:src/test/resources/2/film35.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/g6afc4331bd08jn54e51n.jpg"),
                            "Время расплаты",
                            "Confidential Informant",
                            2023,
                            "США",
                            "Триллеры",
                            new URL("file:src/test/resources/3/film4.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/26/cad37a897a979yx13r88d.jpg"),
                            "Лесной разбойник",
                            "Der Räuber Hotzenplotz / The Robber Hotzenplotz",
                            2022,
                            "Германия",
                            "Фэнтези",
                            new URL("file:src/test/resources/5/film33.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/3/d469ac2fba218dr66i21h.jpg"),
                            "Стюарт Ли: Торнадо",
                            "Stewart Lee: Tornado",
                            2022,
                            "Великобритания",
                            "Стендап",
                            new URL("file:src/test/resources/4/film10.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/11/d25bb667a137ero93u58f.jpg"),
                            "Банды Парижа",
                            "Apaches / Apaches: Gang of Paris",
                            2023,
                            "Франция",
                            "Боевики",
                            new URL("file:src/test/resources/3/film30.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/u3ff0de251507qo70c34x.jpg"),
                            "Нацисты в Нюрнберге: Утраченные свидетельства",
                            "Nazis at Nuremberg: The Lost Testimony",
                            2022,
                            "США",
                            "Документальные",
                            new URL("file:src/test/resources/3/film20.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/30/c7c1579c86c42mh21h77s.jpg"),
                            "Загадка оборотня",
                            "Jacky Caillou",
                            2022,
                            "Франция",
                            "Фэнтези",
                            new URL("file:src/test/resources/3/film17.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/7/5/w5a2f91469d5cnn79p82q.jpeg"),
                            "Wham!",
                            "Wham!",
                            2023,
                            "Великобритания",
                            "Документальные",
                            new URL("file:src/test/resources/1/film12.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/6/27/acb98458164e0lo29a78o.jpg"),
                            "Искупление Габриэля: часть первая",
                            "Gabriel's Redemption: Part One",
                            2023,
                            "США",
                            "Мелодрамы",
                            new URL("file:src/test/resources/5/film6.html"),
                            null),
                    new Film(
                            new URL("https://static.hdrezka.ac/i/2023/4/3/d6a59e4fcbadcva99g69v.jpg"),
                            "Принц пустыни",
                            "Zodi & Tehu, frères du désert / Princes of the Desert",
                            2023,
                            "Франция",
                            "Приключения",
                            new URL("file:src/test/resources/2/film25.html"),
                            null)
            );
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }
}
